part of 'app_theme.dart';
  
final _dark = AppTheme._(
  articleListEndSleepingCatColor: AppColor.grayColor0,
  mainBackgroundColor: AppColor.blackColor0,
  articleBorderColor: AppColor.blackColor2,
  loaderColor: AppColor.whiteColor4,
  articleBackgroundColor: AppColor.blackColor1,
  articleViewCountIconColor: AppColor.grayColor2,
  articleViewCountIconInvertedColor: AppColor.whiteColor0,
  articleReactionsBackgroundColor: AppColor.blackColor0,
  articleReactionsBorderColor: AppColor.blackColor2,
  articleReactionBorderColor: AppColor.blackColor1,
  readUsTelegramButtonColor: AppColor.blackColor1,
  readUsTelegramButtonBorderColor: AppColor.blackColor2,
  readUsTelegramButtonIconColor: AppColor.blueColor0,
  articlesSortColor: AppColor.blackColor1,
  articlesSortBorderColor: AppColor.blackColor2,
  articlesFilterOverlayCloseButtonIconColor: AppColor.grayColor2,
  articlesFilterOverlayApplyButtonColor: AppColor.grayColor5,
  articlesFilterOverlayIsForBeginnerCheckboxColor: AppColor.greenColor0,
  articlesFilterOverlayColor: AppColor.blackColor1,
  articlesFilterOverlayCleanOutButtonIconColor: AppColor.grayColor0,
  articlesFilterButtonColor: AppColor.blackColor1,
  articlesFilterButtonBorderColor: AppColor.blackColor2,
  articlesFilterOverlayCleanOutButtonActiveColor: AppColor.grayColor5,
  articlesFilterOverlayCleanOutButtonBorderActiveColor: AppColor.greenColor0,
  articlesFilterOverlayIsForBeginnerCheckboxCheckColor: AppColor.whiteColor0,
  articlesFilterOverlayIsForBeginnerCheckboxCheckFillActiveColor: AppColor.greenColor0,
  articlesFiltersAcitveIndicatorColor: AppColor.greenColor0,
  articleAuthorNameTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor3,
  ),
  articleAuthorNameInvertedTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.whiteColor0,
  ),
  articleTitleTextStyle: _fontFamilyInter(
    fontSize: 24,
    height: 32 / 24,
    fontWeight: FontWeight.w600,
    color: AppColor.whiteColor4,
  ),
  articleTitleInvertedTextStyle: _fontFamilyInter(
    fontSize: 24,
    height: 32 / 24,
    fontWeight: FontWeight.w600,
    color: AppColor.whiteColor0,
  ),
  articleViewCountTextStyle: _fontFamilyInter(
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: AppColor.grayColor2,
  ),
  articleViewCountInvertedTextStyle: _fontFamilyInter(
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: AppColor.whiteColor0,
  ),
  articleDescriptionTextStyle: _fontFamilyInter(
    fontSize: 18,
    height: 28 / 18,
    fontWeight: FontWeight.w400,
    color: AppColor.whiteColor4,
  ),
  articleDescriptionInvertedTextStyle: _fontFamilyInter(
    fontSize: 18,
    height: 28 / 18,
    fontWeight: FontWeight.w400,
    color: AppColor.whiteColor0,
  ),
  articleFooterButtonTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor3,
  ),
  articleFooterButtonInvertedTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.whiteColor0,
  ),
  articleFooterButtonActiveTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.greenColor0,
  ),
  articleReactionTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor3,
  ),
  articleListEndSleepingCatTextStyle: _fontFamilyInter(
    fontSize: 20,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor1,
  ),
  articleListEndTelegramTextStyle: _fontFamilyInter(
    fontSize: 20,
    height: 28 / 20,
    fontWeight: FontWeight.w600,
    color: AppColor.whiteColor4,
  ),
  articleListEndTelegramLinkTextStyle: _fontFamilyInter(
    color: AppColor.greenColor1,
    fontSize: 20,
    height: 28 / 20,
    fontWeight: FontWeight.w600,
  ),
  readUsTelegramButtonTextStyle: _fontFamilyInter(
    color: AppColor.grayColor2,
    fontSize: 18,
    fontWeight: FontWeight.w400,
  ),
  articlesSortMenuItemTextStyle: _fontFamilyInter(
    color: AppColor.grayColor2,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  articlesSortButtonTextStyle: _fontFamilyArial.copyWith(
    color: AppColor.grayColor2,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  articlesFilterOverlayHeaderTitleTextStyle: _fontFamilyInter(
    color: AppColor.whiteColor4,
    fontSize: 28,
    fontWeight: FontWeight.w600,
  ),
  articlesFilterOverlayApplyButtonTextStyle: _fontFamilyInter(
    color: AppColor.greenColor0,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  articlesFilterOverlayCleanOutButtonTextStyle: _fontFamilyInter(
    color: AppColor.grayColor3,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  articlesFilterOverlayRubricTitleTextStyle: _fontFamilyInter(
    fontSize: 18,
    fontWeight: FontWeight.w600,
    color: AppColor.grayColor2,
  ),
  articlesFilterOverlayIsForBeginnerCheckboxTextStyle: _fontFamilyArial.copyWith(
    fontSize: 18,
    height: 24 / 18,
    fontWeight: FontWeight.w400,
    color: AppColor.grayColor2,
  ),
  articlesFilterButtonTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor2,
  ),
  articlesFilterButtonActiveTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor3,
  ),
);