part of 'app_theme.dart';

final _light = AppTheme._( 
  articleListEndSleepingCatColor: AppColor.grayColor4,
  mainBackgroundColor: AppColor.whiteColor1,
  articleBorderColor: AppColor.whiteColor3,
  loaderColor: AppColor.blackColor3,
  articleBackgroundColor: AppColor.whiteColor0,
  articleViewCountIconColor: AppColor.grayColor0,
  articleViewCountIconInvertedColor: AppColor.whiteColor0,
  articleReactionsBackgroundColor: AppColor.whiteColor2,
  articleReactionsBorderColor: AppColor.whiteColor3,
  articleReactionBorderColor: AppColor.whiteColor0,
  readUsTelegramButtonColor: AppColor.whiteColor0,
  readUsTelegramButtonBorderColor: AppColor.whiteColor3,
  readUsTelegramButtonIconColor: AppColor.blueColor0,
  articlesSortColor: AppColor.whiteColor0,
  articlesSortBorderColor: AppColor.whiteColor3,
  articlesFilterOverlayCloseButtonIconColor: AppColor.grayColor0,
  articlesFilterOverlayApplyButtonColor: AppColor.whiteColor5,
  articlesFilterOverlayIsForBeginnerCheckboxColor: AppColor.greenColor1,
  articlesFilterOverlayColor: AppColor.whiteColor0,
  articlesFilterOverlayCleanOutButtonIconColor: AppColor.grayColor4,
  articlesFilterButtonColor: AppColor.whiteColor0,
  articlesFilterButtonBorderColor: AppColor.whiteColor3,
  articlesFilterOverlayCleanOutButtonActiveColor: AppColor.whiteColor5,
  articlesFilterOverlayCleanOutButtonBorderActiveColor: AppColor.greenColor1,
  articlesFilterOverlayIsForBeginnerCheckboxCheckColor: AppColor.whiteColor0,
  articlesFilterOverlayIsForBeginnerCheckboxCheckFillActiveColor: AppColor.greenColor1,
  articlesFiltersAcitveIndicatorColor: AppColor.greenColor1,
  articleAuthorNameTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor1,
  ),
  articleAuthorNameInvertedTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.whiteColor0,
  ),
  articleTitleTextStyle: _fontFamilyInter(
    fontSize: 24,
    height: 32 / 24,
    fontWeight: FontWeight.w600,
    color: AppColor.blackColor3,
  ),
  articleTitleInvertedTextStyle: _fontFamilyInter(
    fontSize: 24,
    height: 32 / 24,
    fontWeight: FontWeight.w600,
    color: AppColor.whiteColor0,
  ),
  articleViewCountTextStyle: _fontFamilyInter(
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: AppColor.grayColor0,
  ),
  articleViewCountInvertedTextStyle: _fontFamilyInter(
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: AppColor.whiteColor0,
  ),
  articleDescriptionTextStyle: _fontFamilyInter(
    fontSize: 18,
    height: 28 / 18,
    fontWeight: FontWeight.w400,
    color: AppColor.blackColor3,
  ),
  articleDescriptionInvertedTextStyle: _fontFamilyInter(
    fontSize: 18,
    height: 28 / 18,
    fontWeight: FontWeight.w400,
    color: AppColor.whiteColor0,
  ),
  articleFooterButtonTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor1,
  ),
  articleFooterButtonInvertedTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.whiteColor0,
  ),
  articleFooterButtonActiveTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.greenColor1,
  ),
  articleReactionTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor1,
  ),
  articleListEndSleepingCatTextStyle: _fontFamilyInter(
    fontSize: 20,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor1,
  ),
  articleListEndTelegramTextStyle: _fontFamilyInter(
    fontSize: 20,
    height: 28 / 20,
    fontWeight: FontWeight.w600,
    color: AppColor.blackColor3,
  ),
  articleListEndTelegramLinkTextStyle: _fontFamilyInter(
    color: AppColor.greenColor1,
    fontSize: 20,
    height: 28 / 20,
    fontWeight: FontWeight.w600,
  ),
  readUsTelegramButtonTextStyle: _fontFamilyInter(
    color: AppColor.blackColor3,
    fontSize: 18,
    fontWeight: FontWeight.w400,
  ),
  articlesSortMenuItemTextStyle: _fontFamilyInter(
    color: AppColor.grayColor0,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  articlesSortButtonTextStyle: _fontFamilyArial.copyWith(
    color: AppColor.grayColor0,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  articlesFilterOverlayHeaderTitleTextStyle: _fontFamilyInter(
    color: AppColor.blackColor3,
    fontSize: 28,
    fontWeight: FontWeight.w600,
  ),
  articlesFilterOverlayApplyButtonTextStyle: _fontFamilyInter(
    color: AppColor.greenColor1,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  articlesFilterOverlayCleanOutButtonTextStyle: _fontFamilyInter(
    color: AppColor.grayColor1,
    fontSize: 16,
    fontWeight: FontWeight.w500,
  ),
  articlesFilterOverlayRubricTitleTextStyle: _fontFamilyInter(
    fontSize: 18,
    fontWeight: FontWeight.w600,
    color: AppColor.grayColor0,
  ),
  articlesFilterOverlayIsForBeginnerCheckboxTextStyle: _fontFamilyArial.copyWith(
    fontSize: 18,
    height: 24 / 18,
    fontWeight: FontWeight.w400,
    color: AppColor.grayColor0,
  ),
  articlesFilterButtonTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor0,
  ),
  articlesFilterButtonActiveTextStyle: _fontFamilyInter(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColor.grayColor1,
  ),
);