name: tproger_mobile_app_widgetbook
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^2.4.1 
  tproger_mobile_app:
    path: ../../tproger_mobile_app

dev_dependencies:
  flutter_lints: ^2.0.0
