name: tproger_mobile_app_widgetbook
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^2.4.1 
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  tproger_mobile_app:
    path: ../../tproger_mobile_app
  tproger_mobile_app_assets:
    path: ../tproger_mobile_app_assets
  
dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - packages/tproger_mobile_app_assets/images
    - packages/tproger_mobile_app_assets/fonts